name: sinteticolima
description: "Ssitema de control del sintetico Lima"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

  # Estado y arquitectura
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  dartz: ^0.10.1

  # Network
  dio: ^5.7.0

  # Utilidades
  intl: ^0.19.0
  url_launcher: ^6.3.1
  table_calendar: ^3.1.2

  # Almacenamiento local
  shared_preferences: ^2.3.3

  # Routing
  go_router: ^14.6.2

  # InyecciÃ³n de dependencias
  get_it: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # Assets
  assets:
    - src/images/
    - src/images/logo.jpeg